---
title: "Holte New Model "
author: "Ellie Mainou"
date: "3/29/2021"
output: html_document
---

# Import dataset and relevant matrices 
```{r}
set.seed(1234)
#Import modified dataset and make sure that it reads as numbers
library(readxl)
library(readr)
library(deSolve)
```

```{r}
#RV217 Dataset
AcuteData <- read.csv("HIV R files/Acute Infection Models/RV217ForModels4.csv", header=TRUE)
#Matrix that contains initial parameter values for each patient
DDDIPrmIV <- as.data.frame(read_excel("HIV R files/Acute Infection Models/Model Fitting/DDDI_RV217_PrmIV.xlsx"))
```

```{r}
ID<-unique(AcuteData$ID)  #participant IDs
observations= length(ID)

#Setup 
d=0.01
T.start=10^6

names<-c("ID","log10p",  "delta", "c", "r", "gamma", "t0", "error value", "n", "nll", "AIC", "AICc", "BIC")

#Equations
DDDI.model <- function (t, x, params) {
 T <- x[1]
 I <- x[2]
 V <- x[3]
 d=d
 T.start=T.start
 log10p <- params[1]
 delta <- params[2]
 c <- params[3]
 r<-params[4]
 gamma<-params[5]
 t0<-params[6]
 k <- ( r*(c+r) ) / ( 10^log10p*T.start )
 dT <- d*T.start -d*T - k*T*V 
 dI <- k*T*V - delta*I^(gamma+1)
 dV <- 10^log10p*I - c*V
 list(c(dT,dI,dV))
}

#Objective function
sse.sir.DDDI <- function(params0, data, time.points) {
   log10p <- params0[1]
   delta <- params0[2]
   c <- params0[3]
   r <- params0[4]
   gamma <- params0[5]
   t0 <- params0[6]
   T0 <- x_init[1]
   I0 <- x_init[2]
   V0 <- x_init[3]
   out <-as.data.frame(ode(y= c(T=T0, I=I0,V=V0), times=c(t0, time.points), DDDI.model, parms=c(log10p, delta, c, r, gamma, t0), method="lsoda"))
   outV <- out$V[2:length(out$V)]
   sse <- sum( (log10(outV) - data$log10vl)^2 )/n
}

#Simulate with fitted values 
Model.DDDI <- function(t, y, parms) { 
  with(as.list(c(y,parms)),{  
    k <- ( r*(c+r) ) / ( 10^log10p*T.start )
    dT <- d*T.start -d*T - k*T*V 
    dI <- k*T*V - delta*I^(gamma+1)
    dV <- 10^log10p*I - c*V 
    dy=c(dT, dI, dV)
    return(list(dy))
  }) 
} 

k<-length(c("log10p", "delta", "c", "r", "gamma", "t0")) #number of parameters in the model 

```

```{r}
#Create matrix that contains fitted values for each patient. 
DDDIFittedPrms<-as.data.frame(matrix(data=NA, nrow = observations, ncol= length(names)))
colnames(DDDIFittedPrms)<-names
DDDIFittedPrms$ID<-ID

#Optimize for each individual
for(i in 47:observations){
  #Data
  patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
  #initial parameter values
  params0 <- c(log10p=as.numeric(DDDIPrmIV$log10p[i]), delta=as.numeric(DDDIPrmIV$delta[i]), c=as.numeric(DDDIPrmIV$c[i]), r=as.numeric(DDDIPrmIV$r[i]), gamma=(as.numeric(DDDIPrmIV$gamma[i])-1), t0=as.numeric(DDDIPrmIV$t0[i]))
  
  #initial conditions
  x_init <- c(T=T.start, I=as.numeric(DDDIPrmIV$c[i])*1/(10^as.numeric(DDDIPrmIV$log10p[i])), V=1)

  #Fitting step
  fit0 <- optim(params0, sse.sir.DDDI, data=vldata, time.points=c(time.points), method="L-BFGS-B", lower=c(0.001, 0.001, 0.001, 0.001, 0.001, -50),  upper= c(5, 5, 200, 5, 20, 10))
  DDDIFittedPrms$log10p[i]=fit0$par[1]
  DDDIFittedPrms$delta[i]=fit0$par[2]
  DDDIFittedPrms$c[i]=fit0$par[3]
  DDDIFittedPrms$r[i]=fit0$par[4]
  DDDIFittedPrms$gamma[i]=fit0$par[5]
  DDDIFittedPrms$t0[i]=fit0$par[6]
  DDDIFittedPrms$`error value`[i]=fit0$value
}

x<-c(3, 12, 31, 32, 34, 46, 54)
for(i in x){
  #Data
  patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
  #initial parameter values
  params0 <- c(log10p=as.numeric(DDDIPrmIV$log10p[i]), delta=as.numeric(DDDIPrmIV$delta[i]), c=as.numeric(DDDIPrmIV$c[i]), r=as.numeric(DDDIPrmIV$r[i]), gamma=(as.numeric(DDDIPrmIV$gamma[i])-1), t0=as.numeric(DDDIPrmIV$t0[i]))
  
  #initial conditions
  x_init <- c(T=T.start, I=as.numeric(DDDIPrmIV$c[i])*1/(10^as.numeric(DDDIPrmIV$log10p[i])), V=1)

  #Fitting step
  fit0 <- optim(params0, sse.sir.DDDI, data=vldata, time.points=c(time.points))
  DDDIFittedPrms$log10p[i]=fit0$par[1]
  DDDIFittedPrms$delta[i]=fit0$par[2]
  DDDIFittedPrms$c[i]=fit0$par[3]
  DDDIFittedPrms$r[i]=fit0$par[4]
  DDDIFittedPrms$gamma[i]=fit0$par[5]
  DDDIFittedPrms$t0[i]=fit0$par[6]
  DDDIFittedPrms$`error value`[i]=fit0$value
}

write.csv(DDDIFittedPrms, file="DDDIFittedPrms_1.csv")

```


```{r}
pdf("DDDIFitsRV217_1.pdf")

for (i in 1:observations){
  #Data
  patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
 init.cond=c(T=T.start, I=DDDIFittedPrms$c[i]*1/(10^DDDIFittedPrms$log10p[i]), V=1)
  

  parameters=list(    
  d=d,
  T.start=T.start,
  log10p=DDDIFittedPrms$log10p[i],
  delta=DDDIFittedPrms$delta[i],
  c=DDDIFittedPrms$c[i],
  r=DDDIFittedPrms$r[i], 
  gamma=DDDIFittedPrms$gamma[i],
  t0=DDDIFittedPrms$t0[i]
  )
  
soln=as.data.frame(ode(y=init.cond, times=seq(DDDIFittedPrms$t0[i], max(time.points)+1, 1), Model.DDDI, parms=parameters, hmax=0.01))

#Plot results
ID.current <- ID[i]
bquote(ID == ID.current)
bquote(ID == .(ID.current))

  plot(soln$time, log10(soln$V), xlim=c(DDDIFittedPrms$t0[i], max(time.points)), col="red",type="l", ylim=c(0, 10), xlab="Time (days)", ylab="log10 viral load", main = bquote(ID == .(ID.current)))
  par(new=TRUE)
  plot(vldata$time.points, vldata$log10vl,col="black", xlim=c(DDDIFittedPrms$t0[i], max(time.points)), ylim=c(0, 10), xlab="", ylab="")
legend("topright", legend=c("Data", "Model"), col=c("black", "red"), lty=1, cex=0.9)

#Calculate AIC, BIC, AICc
  DDDIFittedPrms$n[i]=n

  soln<-soln[2:nrow(soln), ]
  outV <- soln$V[time.points]
  sse <- sum( (log10(outV) - vldata$log10vl)^2 )

  nll<-log(sse) * (n/2) - n * (log(n) - log(2 * pi) - 1)/2

  DDDIFittedPrms$nll[i]<-nll

  #Calculate AIC
  DDDIFittedPrms$AIC[i]=2*k+2*nll

  #Calculate BIC
  DDDIFittedPrms$BIC[i]=log(n)*k+2*nll

  #Calculate AICc
  DDDIFittedPrms$AICc[i]=DDDIFittedPrms$AIC[i]+ (2*k^2+2*k)/(n-k-1)


}

hist(DDDIFittedPrms$log10p, breaks=10, xlab = "log10(p)",main="")
hist(log10(DDDIFittedPrms$delta), breaks=10, xlab = "log10(delta)",main="")
hist(DDDIFittedPrms$r, breaks=10, xlab = "r (fitted)",main="")
hist(DDDIFittedPrms$c, breaks=10, xlab = "c",main="")
hist(DDDIFittedPrms$`error value`, breaks=10, xlab = "error value",main="")
hist(DDDIFittedPrms$AIC, breaks=10, xlab = "AIC",main="")
hist(DDDIFittedPrms$BIC, breaks=10, xlab = "BIC",main="")
hist(DDDIFittedPrms$AICc, breaks=10, xlab = "AICc",main="")

dev.off()

write.csv(DDDIFittedPrms, file="DDDIFittedPrms_1.csv")

```


```{r}
i=45
  #Data
  patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
  #initial parameter values
  params0 <- c(log10p=as.numeric(DDDIPrmIV$log10p[i]), delta=as.numeric(DDDIPrmIV$delta[i]), c=as.numeric(DDDIPrmIV$c[i]), r=as.numeric(DDDIPrmIV$r[i]), gamma=(as.numeric(DDDIPrmIV$gamma[i])-1), t0=as.numeric(DDDIPrmIV$t0[i])+5)
  
  #initial conditions
  x_init <- c(T=T.start, I=as.numeric(DDDIPrmIV$c[i])*1/(10^as.numeric(DDDIPrmIV$log10p[i])), V=1)

  #Fitting step
  fit0 <- optim(params0, sse.sir.DDDI, data=vldata, time.points=c(time.points))
  DDDIFittedPrms$log10p[i]=fit0$par[1]
  DDDIFittedPrms$delta[i]=fit0$par[2]
  DDDIFittedPrms$c[i]=fit0$par[3]
  DDDIFittedPrms$r[i]=fit0$par[4]
  DDDIFittedPrms$gamma[i]=fit0$par[5]
  DDDIFittedPrms$t0[i]=fit0$par[6]
  DDDIFittedPrms$`error value`[i]=fit0$value

write.csv(DDDIFittedPrms, file="DDDIFittedPrms_2.csv")
```


```{r}
pdf("DDDIFitsRV217_2.pdf")

for (i in 1:observations){
  #Data
  patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
 init.cond=c(T=T.start, I=DDDIFittedPrms$c[i]*1/(10^DDDIFittedPrms$log10p[i]), V=1)
  

  parameters=list(    
  d=d,
  T.start=T.start,
  log10p=DDDIFittedPrms$log10p[i],
  delta=DDDIFittedPrms$delta[i],
  c=DDDIFittedPrms$c[i],
  r=DDDIFittedPrms$r[i], 
  gamma=DDDIFittedPrms$gamma[i],
  t0=DDDIFittedPrms$t0[i]
  )
  
soln=as.data.frame(ode(y=init.cond, times=seq(DDDIFittedPrms$t0[i], max(time.points)+1, 1), Model.DDDI, parms=parameters, hmax=0.01))

#Plot results
ID.current <- ID[i]
bquote(ID == ID.current)
bquote(ID == .(ID.current))

  plot(soln$time, log10(soln$V), xlim=c(DDDIFittedPrms$t0[i], max(time.points)), col="red",type="l", ylim=c(0, 10), xlab="Time (days)", ylab="log10 viral load", main = bquote(ID == .(ID.current)))
  par(new=TRUE)
  plot(vldata$time.points, vldata$log10vl,col="black", xlim=c(DDDIFittedPrms$t0[i], max(time.points)), ylim=c(0, 10), xlab="", ylab="")
legend("topright", legend=c("Data", "Model"), col=c("black", "red"), lty=1, cex=0.9)

#Calculate AIC, BIC, AICc
  DDDIFittedPrms$n[i]=n

  soln<-soln[2:nrow(soln), ]
  outV <- soln$V[time.points]
  sse <- sum( (log10(outV) - vldata$log10vl)^2 )

  nll<-log(sse) * (n/2) - n * (log(n) - log(2 * pi) - 1)/2

  DDDIFittedPrms$nll[i]<-nll

  #Calculate AIC
  DDDIFittedPrms$AIC[i]=2*k+2*nll

  #Calculate BIC
  DDDIFittedPrms$BIC[i]=log(n)*k+2*nll

  #Calculate AICc
  DDDIFittedPrms$AICc[i]=DDDIFittedPrms$AIC[i]+ (2*k^2+2*k)/(n-k-1)


}

hist(DDDIFittedPrms$log10p, breaks=10, xlab = "log10(p)",main="")
hist(log10(DDDIFittedPrms$delta), breaks=10, xlab = "log10(delta)",main="")
hist(DDDIFittedPrms$r, breaks=10, xlab = "r (fitted)",main="")
hist(DDDIFittedPrms$c, breaks=10, xlab = "c",main="")
hist(DDDIFittedPrms$`error value`, breaks=10, xlab = "error value",main="")
hist(DDDIFittedPrms$AIC, breaks=10, xlab = "AIC",main="")
hist(DDDIFittedPrms$BIC, breaks=10, xlab = "BIC",main="")
hist(DDDIFittedPrms$AICc, breaks=10, xlab = "AICc",main="")

dev.off()

Summary_DDDI<-as.data.frame(matrix(data=NA, nrow=3, ncol=k+1))
colnames(Summary_DDDI)=c("log10p","delta", "c", "r", "gamma", "t0", "k")
rownames(Summary_DDDI)=c("mean", "median", "sd")


for (j in 1:k){
  Summary_DDDI[1, j]=mean(DDDIFittedPrms[, 1+j])
  Summary_DDDI[2, j]=median(DDDIFittedPrms[, 1+j])
  Summary_DDDI[3, j]=sd(DDDIFittedPrms[, 1+j])
}

mass.action.inf<-( DDDIFittedPrms$r*(DDDIFittedPrms$c+DDDIFittedPrms$r) ) / ( 10^(DDDIFittedPrms$log10p)*T.start )
j=7
  Summary_DDDI[1, j]=mean(mass.action.inf)
  Summary_DDDI[2, j]=median(mass.action.inf)
  Summary_DDDI[3, j]=sd(mass.action.inf)

write.csv(Summary_DDDI, file="Summary_DDDI_2.csv")

write.csv(DDDIFittedPrms, file="DDDIFittedPrms_2.csv")

```

Now fit again the study participants for whom you removed a data point. 

```{r}
#RV217 Dataset
AcuteData <- read.csv("HIV R files/Acute Infection Models/RV217ForModels3.csv", header=TRUE)
#Matrix that contains initial parameter values for each patient
DDDIPrmIV <- as.data.frame(read_excel("HIV R files/Acute Infection Models/Model Fitting/DDDI_RV217_PrmIV.xlsx"))
DDDIFittedPrms <- as.data.frame(read_csv("HIV R files/Acute Infection Models/Model Fitting/DDDIFittedPrms_2.csv"))
```


```{r}
ID.remove<-c(20382, 20799, 20863, 21006, 21010)

for(j in 1:length(ID.remove)){
  #Data
  patient.current<-AcuteData[which(AcuteData$ID==ID.remove[j]), ]
  i=which(DDDIFittedPrms$ID==ID.remove[j])
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
  #initial parameter values
  params0 <- c(log10p=as.numeric(DDDIPrmIV$log10p[i]), delta=as.numeric(DDDIPrmIV$delta[i]), c=as.numeric(DDDIPrmIV$c[i]), r=as.numeric(DDDIPrmIV$r[i]), gamma=(as.numeric(DDDIPrmIV$gamma[i])-1), t0=as.numeric(DDDIPrmIV$t0[i]))
  
  #initial conditions
  x_init <- c(T=T.start, I=as.numeric(DDDIPrmIV$c[i])*1/(10^as.numeric(DDDIPrmIV$log10p[i])), V=1)

  #Fitting step
  fit0 <- optim(params0, sse.sir.DDDI, data=vldata, time.points=c(time.points), method="L-BFGS-B", lower=c(0.001, 0.001, 0.001, 0.001, 0.001, -50),  upper= c(5, 5, 200, 5, 20, 10))
  DDDIFittedPrms$log10p[i]=fit0$par[1]
  DDDIFittedPrms$delta[i]=fit0$par[2]
  DDDIFittedPrms$c[i]=fit0$par[3]
  DDDIFittedPrms$r[i]=fit0$par[4]
  DDDIFittedPrms$gamma[i]=fit0$par[5]
  DDDIFittedPrms$t0[i]=fit0$par[6]
  DDDIFittedPrms$`error value`[i]=fit0$value
}

#For ID=40168, t0>0. refit with t0<0

i=40
#Data
  patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
  #initial parameter values
  params0 <- c(log10p=as.numeric(DDDIPrmIV$log10p[i]), delta=as.numeric(DDDIPrmIV$delta[i]), c=as.numeric(DDDIPrmIV$c[i]), r=as.numeric(DDDIPrmIV$r[i]), gamma=(as.numeric(DDDIPrmIV$gamma[i])-1), t0=as.numeric(DDDIPrmIV$t0[i])-7)
  
  #initial conditions
  x_init <- c(T=T.start, I=as.numeric(DDDIPrmIV$c[i])*1/(10^as.numeric(DDDIPrmIV$log10p[i])), V=1)

  #Fitting step
  fit0 <- optim(params0, sse.sir.DDDI, data=vldata, time.points=c(time.points), method="L-BFGS-B", lower=c(0.001, 0.001, 0.001, 0.001, 0.001, -50),  upper= c(5, 5, 200, 5, 20, 0))
  DDDIFittedPrms$log10p[i]=fit0$par[1]
  DDDIFittedPrms$delta[i]=fit0$par[2]
  DDDIFittedPrms$c[i]=fit0$par[3]
  DDDIFittedPrms$r[i]=fit0$par[4]
  DDDIFittedPrms$gamma[i]=fit0$par[5]
  DDDIFittedPrms$t0[i]=fit0$par[6]
  DDDIFittedPrms$`error value`[i]=fit0$value
  
  
i=which(ID==10204)

#Data
patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
time.points<-patient.current$days
log10vl<-patient.current$log10VL
vldata <- data.frame(time.points,log10vl)
n=nrow(vldata)

#initial parameter values
params0 <- c(log10p=as.numeric(DDDIPrmIV$log10p[i]), delta=as.numeric(DDDIPrmIV$delta[i]), 
             c=as.numeric(DDDIPrmIV$c[i]), r=as.numeric(DDDIPrmIV$r[i]), 
             gamma=1.01, t0=as.numeric(DDDIPrmIV$t0[i])-10)

#initial conditions
x_init <- c(T=T.start, I=as.numeric(DDDIPrmIV$c[i])*1/(10^as.numeric(DDDIPrmIV$log10p[i])), V=1)

#Fitting step
fit0 <- optim(params0, sse.sir.DDDI, data=vldata, time.points=c(time.points), method="L-BFGS-B", lower=c(0.001, 0.001, 0.001, 0.001, 0.001, -50),  upper= c(5, 5, 200, 5, 20, 0))
DDDIFittedPrms$log10p[i]=fit0$par[1]
DDDIFittedPrms$delta[i]=fit0$par[2]
DDDIFittedPrms$c[i]=fit0$par[3]
DDDIFittedPrms$r[i]=fit0$par[4]
DDDIFittedPrms$gamma[i]=fit0$par[5]
DDDIFittedPrms$t0[i]=fit0$par[6]
DDDIFittedPrms$`error value`[i]=fit0$value

i=which(ID==10374)

#Data
patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
time.points<-patient.current$days
log10vl<-patient.current$log10VL
vldata <- data.frame(time.points,log10vl)
n=nrow(vldata)

#initial parameter values
params0 <- c(log10p=as.numeric(DDDIPrmIV$log10p[i]), delta=as.numeric(DDDIPrmIV$delta[i]), 
             c=as.numeric(DDDIPrmIV$c[i]), r=as.numeric(DDDIPrmIV$r[i]), 
             gamma=1.01, t0=as.numeric(DDDIPrmIV$t0[i])-5)

#initial conditions
x_init <- c(T=T.start, I=as.numeric(DDDIPrmIV$c[i])*1/(10^as.numeric(DDDIPrmIV$log10p[i])), V=1)

#Fitting step
fit0 <- optim(params0, sse.sir.DDDI, data=vldata, time.points=c(time.points), method="L-BFGS-B", lower=c(0.001, 0.001, 0.001, 0.001, 0.001, -50),  upper= c(5, 5, 200, 5, 20, 0))
DDDIFittedPrms$log10p[i]=fit0$par[1]
DDDIFittedPrms$delta[i]=fit0$par[2]
DDDIFittedPrms$c[i]=fit0$par[3]
DDDIFittedPrms$r[i]=fit0$par[4]
DDDIFittedPrms$gamma[i]=fit0$par[5]
DDDIFittedPrms$t0[i]=fit0$par[6]
DDDIFittedPrms$`error value`[i]=fit0$value

```

```{r}
pdf("DDDIFitsRV217_3.pdf")

for (i in 1:observations){
  #Data
  patient.current<-AcuteData[which(AcuteData$ID==ID[i]), ]
  time.points<-patient.current$days
  log10vl<-patient.current$log10VL
  vldata <- data.frame(time.points,log10vl)
  n=nrow(vldata)
  
 init.cond=c(T=T.start, I=DDDIFittedPrms$c[i]*1/(10^DDDIFittedPrms$log10p[i]), V=1)
  

  parameters=list(    
  d=d,
  T.start=T.start,
  log10p=DDDIFittedPrms$log10p[i],
  delta=DDDIFittedPrms$delta[i],
  c=DDDIFittedPrms$c[i],
  r=DDDIFittedPrms$r[i], 
  gamma=DDDIFittedPrms$gamma[i],
  t0=DDDIFittedPrms$t0[i]
  )
  
soln=as.data.frame(ode(y=init.cond, times=seq(DDDIFittedPrms$t0[i], max(time.points)+1, 1), Model.DDDI, parms=parameters, hmax=0.01))

#Plot results
ID.current <- ID[i]
bquote(ID == ID.current)
bquote(ID == .(ID.current))

  plot(soln$time, log10(soln$V), xlim=c(DDDIFittedPrms$t0[i], max(time.points)), col="red",type="l", ylim=c(0, 10), xlab="Time (days)", ylab="log10 viral load", main = bquote(ID == .(ID.current)))
  par(new=TRUE)
  plot(vldata$time.points, vldata$log10vl,col="black", xlim=c(DDDIFittedPrms$t0[i], max(time.points)), ylim=c(0, 10), xlab="", ylab="")
legend("topright", legend=c("Data", "Model"), col=c("black", "red"), lty=1, cex=0.9)

#Calculate AIC, BIC, AICc
  DDDIFittedPrms$n[i]=n

  soln<-soln[2:nrow(soln), ]
  outV <- soln$V[time.points]
  sse <- sum( (log10(outV) - vldata$log10vl)^2 )

  nll<-log(sse) * (n/2) - n * (log(n) - log(2 * pi) - 1)/2

  DDDIFittedPrms$nll[i]<-nll

  #Calculate AIC
  DDDIFittedPrms$AIC[i]=2*k+2*nll

  #Calculate BIC
  DDDIFittedPrms$BIC[i]=log(n)*k+2*nll

  #Calculate AICc
  DDDIFittedPrms$AICc[i]=DDDIFittedPrms$AIC[i]+ (2*k^2+2*k)/(n-k-1)


}

hist(DDDIFittedPrms$log10p, breaks=10, xlab = "log10(p)",main="")
hist(log10(DDDIFittedPrms$delta), breaks=10, xlab = "log10(delta)",main="")
hist(DDDIFittedPrms$r, breaks=10, xlab = "r (fitted)",main="")
hist(DDDIFittedPrms$c, breaks=10, xlab = "c",main="")
hist(DDDIFittedPrms$`error value`, breaks=10, xlab = "error value",main="")
hist(DDDIFittedPrms$AIC, breaks=10, xlab = "AIC",main="")
hist(DDDIFittedPrms$BIC, breaks=10, xlab = "BIC",main="")
hist(DDDIFittedPrms$AICc, breaks=10, xlab = "AICc",main="")

dev.off()

Summary_DDDI<-as.data.frame(matrix(data=NA, nrow=3, ncol=k+1))
colnames(Summary_DDDI)=c("log10p","delta", "c", "r", "gamma", "t0", "k")
rownames(Summary_DDDI)=c("mean", "median", "sd")


for (j in 1:k){
  Summary_DDDI[1, j]=mean(DDDIFittedPrms[, 1+j])
  Summary_DDDI[2, j]=median(DDDIFittedPrms[, 1+j])
  Summary_DDDI[3, j]=sd(DDDIFittedPrms[, 1+j])
}

mass.action.inf<-( DDDIFittedPrms$r*(DDDIFittedPrms$c+DDDIFittedPrms$r) ) / ( 10^(DDDIFittedPrms$log10p)*T.start )
j=7
  Summary_DDDI[1, j]=mean(mass.action.inf)
  Summary_DDDI[2, j]=median(mass.action.inf)
  Summary_DDDI[3, j]=sd(mass.action.inf)

write.csv(Summary_DDDI, file="Summary_DDDI_3.csv")

write.csv(DDDIFittedPrms, file="DDDIFittedPrms_3.csv")

```

